import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "광'S Coffee House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <ul className="py-2 text-7xl bg-sky-200 flex gap-7">
            <li>
              <Link href={"/about"}>About</Link>
            </li>
            <li>
              <Link href={"/menu"}>Menu</Link>
            </li>
            <li>
              <Link href={"/q&a"}>Q&A</Link>
            </li>
          </ul>
        </header>
        {children}
        <footer>
          <ul className="text-5xl bg-amber-50 flex gap-7">
            <li>Instargram</li>
            <li>E-Mail</li>
            <li>FaceBook</li>
            <li>YouTube</li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
